services:
  app:
    container_name: "glpi-app"
    build:
      context: ".docker/app"
      args:
        PHP_VERSION: "8.4"
    restart: "unless-stopped"
    volumes:
      - ".:/var/www/glpi:rw"
      - "custom_php_ini:/usr/local/etc/php/custom_conf.d/:rw"
    ports:
      - "8080:80"
      - "9637:9637"
    depends_on:
      - db
    environment:
      # By default the testing env is exposed under the 8080 internal port
      CYPRESS_BASE_URL: http://localhost:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    container_name: "glpi-db"
    image: "mariadb:11.8"
    restart: "unless-stopped"
    volumes:
      - "db:/var/lib/mysql"
      - ".docker/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"
    environment:
      MARIADB_ROOT_PASSWORD: "glpi"
      MARIADB_DATABASE: "glpi"
      MARIADB_USER: "glpi"
      MARIADB_PASSWORD: "glpi"
    expose:
      - "3306"

  mailpit:
    container_name: "glpi-mailpit"
    image: "axllent/mailpit"
    restart: "unless-stopped"
    expose:
      - "1025"
    ports:
      - "8025:8025"

  dbgate:
    container_name: "glpi-dbgate"
    image: "dbgate/dbgate:latest"
    restart: "unless-stopped"
    ports:
      - "8090:3000"
    environment:
      CONNECTIONS: "glpi"

      LABEL_glpi: "GLPI Mysql Server"
      SERVER_glpi: "db"
      USER_glpi: "glpi"
      PASSWORD_glpi: "glpi"
      PORT_glpi: 3306
      ENGINE_glpi: "mysql@dbgate-plugin-mysql"

  # To use as a LDAP connection inside GLPI, you'll need to set the following values:
  # server: openldap
  # port: 1389
  # connection filter: (objectClass=inetOrgPerson)
  # base dn: dc=example,dc=org
  # Use bind: yes
  # Root DN: cn=admin,dc=example,dc=org
  # Password: adminpassword
  # Login field: uid
  # Synchronization field: entryuuid
  # TODO: create a bin/console dev command that create a LDAP server object with
  # the information above to make things even easier ;)
  openldap:
    image: bitnami/openldap:latest
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_ROOT=dc=example,dc=org

volumes:
  db:
  custom_php_ini:
