services:
  app:
    container_name: "glpi-app"
    build:
      context: ".docker/app"
      args:
        PHP_VERSION: "8.4"
    restart: "unless-stopped"
    volumes:
      - ".:/var/www/glpi:rw"
      - "custom_php_ini:/usr/local/etc/php/custom_conf.d/:rw"
    ports:
      - "8080:80"
      - "8090:8090"
      - "9637:9637"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    container_name: "glpi-db"
    image: "mariadb:11.8"
    restart: "unless-stopped"
    volumes:
      - "db:/var/lib/mysql"
      - ".docker/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql"
    environment:
      MARIADB_ROOT_PASSWORD: "glpi"
      MARIADB_DATABASE: "glpi"
      MARIADB_USER: "glpi"
      MARIADB_PASSWORD: "glpi"
    expose:
      - "3306"

  mailpit:
    container_name: "glpi-mailpit"
    image: "axllent/mailpit"
    restart: "unless-stopped"
    expose:
      - "1025"
    ports:
      - "8025:8025"

  dbgate:
    container_name: "glpi-dbgate"
    image: "dbgate/dbgate:latest"
    restart: "unless-stopped"
    ports:
      - "8090:3000"
    environment:
      CONNECTIONS: "glpi"

      LABEL_glpi: "GLPI Mysql Server"
      SERVER_glpi: "db"
      USER_glpi: "glpi"
      PASSWORD_glpi: "glpi"
      PORT_glpi: 3306
      ENGINE_glpi: "mysql@dbgate-plugin-mysql"

volumes:
  db:
  custom_php_ini:
