name: "Code coverage schedule"

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  run-coverage-workflow:
    permissions:
      contents: "read"
    name: "Run coverage workflow"
    uses: "glpi-project/glpi/.github/workflows/coverage.yml@main"
    with:
      branch: "main"
