name: Update PLAYWRIGHT_VERSION variable when dependabot update our dependencies

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main, 11.0/bugfixes]
    paths:
      - "package.json"

jobs:
  sync:
    permissions:
      contents: write
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Extract Playwright version
        id: version
        run: |
          VERSION=$(jq -r '.devDependencies.playwright // .dependencies.playwright' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update Makefile
        run: |
          sed -i "s/^PLAYWRIGHT_VERSION := .*/PLAYWRIGHT_VERSION := ${VERSION}/" Makefile

      - name: Commit changes back to the PR
        run: |
          if [[ `git status --porcelain` ]]; then
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git add Makefile
              git commit -m "chore: sync PLAYWRIGHT_VERSION with package.json"
              git push
          else
              echo "No changes"
          fi
